Repository KIT-IAI/pyWATTS, pull requests merged in 2021-07, with the labels that each got.

#128 Added summary parameter to ensure backward compatibility
  CHANGELOG.md
  pywatts/core/pipeline.py
  tests/unit/core/test_pipeline.py
Labels: core, enhancement

#134 Ensure that summaries are always created.
  pywatts/core/pipeline.py
Labels: bug

#135 Use raise Exception from Exception if an exception is catched and than a new one raised.
  CHANGELOG.md
  pywatts/core/step_factory.py
  pywatts/modules/calendar_extraction.py
  pywatts/modules/change_direction.py
  pywatts/modules/clock_shift.py
  pywatts/modules/sample_module.py
Labels: bug

#125 Extract the time index from the correct input in rolling rmse.
  CHANGELOG.md
  pywatts/modules/rolling_metric_base.py
  tests/unit/modules/test_rolling_rmse.py
Labels: bug, module
