Repository KIT-IAI/pyWATTS, pull requests merged in 2021-06, with the labels that each got.

#96 Optional pipeline path and less aggressive directory creation
  CHANGELOG.md
  pywatts/core/filemanager.py
  pywatts/core/pipeline.py
Labels: enhancement

#101 Update python-app.yml
  .github/workflows/python-app.yml
Labels: ci

#108 Fix mask for weekend and public holidays.
  CHANGELOG.md
  pywatts/modules/rolling_base.py
  pywatts/modules/rolling_mean.py
  tests/unit/modules/test_rolling_mean.py
Labels: bug, module

#85 Feature/34 summaries
  CHANGELOG.md
  README.md
  docs/source/api/pywatts.core.rst
  docs/source/api/pywatts.modules.rst
  docs/source/api/pywatts.rst
  docs/source/api/pywatts.summaries.rst
  docs/source/how_to_use.rst
  examples/example.py
  examples/example_day_and_night.py
  examples/example_keras.py
  examples/example_pytorch.py
  pywatts/core/base.py
  pywatts/core/base_step.py
  pywatts/core/base_summary.py
  pywatts/core/pipeline.py
  pywatts/core/step.py
  pywatts/core/step_factory.py
  pywatts/core/step_information.py
  pywatts/core/summary_step.py
  pywatts/modules/rolling_rmse.py
  pywatts/modules/root_mean_squared_error.py
  pywatts/summaries/__init__.py
  pywatts/summaries/rmse_summary.py
  tests/unit/core/test_pipeline.py
  tests/unit/core/test_summary_step.py
  tests/unit/modules/test_rolling_rmse.py
  tests/unit/summaries/test_root_mean_squared_error.py
Labels: core, enhancement
