Repository KIT-IAI/pyWATTS, pull requests merged in 2022-03, with the labels that each got.

#177 Change position of relearning
  .github/workflows/python-app.yml
  CHANGELOG.md
  examples/example_batch_execution.py
  pywatts/core/base.py
  pywatts/core/base_step.py
  pywatts/core/computation_mode.py
  pywatts/core/pipeline.py
  pywatts/core/pipeline_step.py
  pywatts/core/step.py
  pywatts/core/step_factory.py
  tests/unit/core/test_inverse_step.py
  tests/unit/core/test_pipeline.py
  tests/unit/core/test_step.py
Labels: core

#186 Update Readme
  README.md
Labels: documentation

#187 Update about_us
  docs/source/about_us.rst
Labels: documentation

#190 Feature/189 fill buffer
  CHANGELOG.md
  examples/example_batch_execution.py
  pywatts/core/base_step.py
  pywatts/core/pipeline.py
  pywatts/core/pipeline_step.py
  pywatts/core/run_setting.py
  pywatts/core/step.py
  pywatts/core/summary_step.py
  tests/unit/core/test_pipeline.py
  tests/unit/core/test_summary_step.py
Labels: enhancement, core

#196 Adding AnomalyGernation modules
  CHANGELOG.md
  pywatts/modules/__init__.py
  pywatts/modules/generation/__init__.py
  pywatts/modules/generation/anomaly_generation_module.py
  pywatts/modules/generation/energy_anomaly_generation_module.py
  pywatts/modules/generation/power_anomaly_generation_module.py
  tests/unit/modules/test_anomaly_generation_module.py
Labels: enhancement

#200 Bugfix/199 time index name
  CHANGELOG.md
  pywatts/core/pipeline.py
  pywatts/modules/wrappers/sklearn_wrapper.py
Labels: bug

#191 Feature/refit conditions
  CHANGELOG.md
  docs/source/api/pywatts.conditions.rst
  docs/source/api/pywatts.core.rst
  docs/source/api/pywatts.rst
  examples/example_batch_execution.py
  pywatts/conditions/__init__.py
  pywatts/conditions/periodic_condition.py
  pywatts/core/base.py
  pywatts/core/base_condition.py
  pywatts/core/base_summary.py
  pywatts/core/step.py
  pywatts/core/step_factory.py
  tests/unit/conditions/__init__.py
  tests/unit/conditions/test_periodic_condition.py
  tests/unit/core/test_pipeline.py
  tests/unit/core/test_step.py
Labels: enhancement, core

#173 Feature/#165 ensemble module
  CHANGELOG.md
  docs/source/api/pywatts.modules.postprocessing.rst
  docs/source/api/pywatts.modules.rst
  pywatts/modules/__init__.py
  pywatts/modules/postprocessing/__init__.py
  pywatts/modules/postprocessing/ensemble.py
  tests/unit/modules/test_ensemble.py
Labels: enhancement, module

#205 Fix problems with summary=false.
  pywatts/core/pipeline.py
  tests/unit/core/test_pipeline.py
Labels: bug, core

#204 Bugfix/online learning in subpipelines
  CHANGELOG.md
  pywatts/core/pipeline.py
Labels: bug, core

#207 Feature/147 get min data
  CHANGELOG.md
  pywatts/core/base.py
  pywatts/core/base_step.py
  pywatts/core/either_or_step.py
  pywatts/core/result_step.py
  pywatts/core/step.py
  pywatts/modules/feature_extraction/rolling_base.py
  pywatts/modules/feature_extraction/trend_extraction.py
  pywatts/modules/preprocessing/clock_shift.py
  pywatts/modules/preprocessing/resampler.py
  pywatts/modules/preprocessing/sampler.py
  tests/unit/core/test_step.py
  tests/unit/core/test_summary_step.py
  tests/unit/modules/test_clock_shift.py
  tests/unit/modules/test_resampler.py
  tests/unit/modules/test_rolling_mean.py
  tests/unit/modules/test_sampler.py
  tests/unit/modules/test_trend_extraction.py
Labels: core, module

#194 Change naming of the metric on the complete time series and adapt tests.
  CHANGELOG.md
  pywatts/summaries/metric_base.py
  tests/unit/summaries/metrics/test_mase.py
  tests/unit/summaries/metrics/test_max_error.py
  tests/unit/summaries/metrics/test_mean_abs_percentage_error.py
  tests/unit/summaries/metrics/test_mean_absolute_error.py
  tests/unit/summaries/metrics/test_min_error.py
  tests/unit/summaries/metrics/test_root_mean_squared_error.py
Labels: bug, module

#214 Bugfix/reset step finished flag
  CHANGELOG.md
  pywatts/core/pipeline.py
Labels: bug
